stages:
  - build
  - release

build_job:
  stage: build
  image: node:alpine
  script:
    - npm install          # Installer les dépendances si nécessaire
    - npm install -g nexe  # Installer Nexe si ce n'est pas déjà fait
    - npm run build        # Build TypeScript dans /dist 
    - nexe --build -i ./dist/index.js -o bin.exe # Cré l'éxécutable avec nexe
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    paths:
      - /bin.exe   # Spécifiez le chemin vers votre binaire pour l'archiver comme artefact
    expire_in: never
    reports:
      dotenv: job.env

create:release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - build_job
  variables:
    TAG: '$CI_COMMIT_SHA'
  script:
    - echo "Create Release $TAG"
    - echo $JOB_ID  
  release:
    name: 'Release $TAG'
    tag_name: '$TAG'
    ref: '$TAG'
    description: 'Release $TAG'
    assets:
      links:
        - name: "ontology-to-synfony-vocabulary.exe"
          url: "https://https://gitlab.irstea.fr/pole-is/ontology-to-synfony-vocabulary/-/jobs/$JOB_ID/artifacts/download"
