stages:
  - build
  - release

build_job:
  stage: build
  image: node:alpine
  script:
    - npm install          # Installer les dépendances si nécessaire
    - npm install -g nexe  # Installer Nexe si ce n'est pas déjà fait
    - npm run build        # Build TypeScript dans /dist 
    - nexe --build -i ./dist/index.js -o bin.exe # Cré l'éxécutable avec nexe

  artifacts:
    paths:
      - /bin.exe   # Spécifiez le chemin vers votre binaire pour l'archiver comme artefact

release_job:
  stage: release
  image: alpine
  script:
    - apk add --no-cache curl  # Installez curl pour les appels API
    - curl --header "PRIVATE-TOKEN: AT-KQXzMZCvv48DkPB4G" --upload-file /bin.exe "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
  dependencies:
    - build_job
  only:
    - tags